### ISSUE TITLE
add support for automatic reset of WireMock's stubs between test execution

### ISSUE THREAD

**Issue by rfelgent** [wiremock/wiremock-spring-boot#30]
Hi @maciejwalkowiak,

I have a feature request: automatic reset of all stubs of each WireMock instance _after_ each test execution.

If you are convinced by that feature request, I will try to provide a PR

**Comment by maciejwalkowiak** [comment]
How this would look like? As an option on annotation?

**Comment by tomasbjerre** [comment]
Is this not what is happening here?
https://github.com/wiremock/wiremock-spring-boot/blob/72bd5867ec4ea8e5a85e96ebea5ea9e2bc60c6a8/src/main/java/org/wiremock/spring/internal/WireMockSpringExtension.java#L26

Also added a test to show this bahavior:
https://github.com/wiremock/wiremock-spring-boot/blob/f2c35d0bc7e22fd230b4d94192e36b39b2ef45fb/wiremock-spring-boot-example/src/test/java/app/ResetWireMockBetweenTest.java

I'm trying to cleanup the issues in this repo, so closing this one. If still relevant, re-open and I'll have a second look.

**Comment by rfelgent** [comment]
Perfect
