### ISSUE TITLE
Switch build to Gradle in order to use the WireMock convention plugin

### ISSUE THREAD

**Issue by tomakehurst** [wiremock/wiremock-spring-boot#44]
### Proposal

Most other WireMock extension projects use WireMock's own plugin for build and release. Since this is quite complex to set up otherwise, suggest we implement this here.

**Comment by tomasbjerre** [comment]
I Switched to this plugin:
https://github.com/wiremock/gradle-wiremock-extension-plugins

I'm not really sure it is correct, since it is now a WireMock extension, we can discuss it in https://github.com/wiremock/community/issues/55

**Comment by tomasbjerre** [comment]
I have made the switch to Gradle and is ready to make first release, just waiting for permission #46
