### ISSUE TITLE
wiremock-standalone dependency version is not up-to-date

### ISSUE THREAD

**Issue by rrymaszewski** [wiremock/wiremock-spring-boot#45]
### Proposal

use newest version of wiremock-standalone - 3.9.1

### References

https://mvnrepository.com/artifact/org.wiremock/wiremock-standalone/3.9.1

**Comment by tomasbjerre** [comment]
Merged, not released.

**Comment by yanivnahoum** [comment]
> Merged, not released.

@tomasbjerre Are there any plans to maintain and release a standalone version? It would be very beneficial seeing that jackson & guava are frequently used by the consuming apps and conflicts are likely.

**Comment by tomasbjerre** [comment]
No not planned.
