### ISSUE TITLE
Release to Central

### ISSUE THREAD

**Issue by tomasbjerre** [wiremock/wiremock-spring-boot#46]
### Summary

- Decide correct `groupId` and get permission https://github.com/wiremock/community/issues/55
- Use correct `package` in the code
- Update README with that `groupId`

**Comment by mmuruev** [comment]
Which repo should I use seems like  `testImplementation "org.wiremock.spring:wiremock-spring-boot:X"` has no effect to me. Exact version also is not helping here.

**Comment by tomasbjerre** [comment]
It is not yet released.

Here is the old readme:
https://github.com/wiremock/wiremock-spring-boot/tree/v2.1.3

**Comment by tomasbjerre** [comment]
https://repo1.maven.org/maven2/org/wiremock/integrations/wiremock-spring-boot/
