### ISSUE TITLE
Add support for meta annotation @EnableWireMock

### ISSUE THREAD

**Issue by rfelgent** [wiremock/wiremock-spring-boot#58]
### Proposal

Hello,

in order to reduce boiler plate code, I would like to have _one_ `@EnableWireMock` meta annotation and re-use it in _several_ ITs.

Here an example code for the desired meta annotation functionality

```
@EnableWireMock(@ConfigureWireMock(
    baseUrlProperties = {
        "app.client-apis.product-aggregate-api.base-path",
        "app.client-apis.rpt-product-api.base-path",
        "app.client-apis.ntz-usage-information-api.base-path",
        "app.client-apis.kmw-participations-api.base-path",
        "app.client-apis.rpt-services-api.base-path"
    }))
public @interface EnableWireMockGvl {

}
```

And re-use it in several ITs, e.g.

```
@SpringBootTest
@EnableWireMockGvl
class ApplicationIT {
}
```

If you are convinced by that feature request, I can try to provide a pull request.

Best regards

**Comment by tomasbjerre** [comment]
I'm convinced! A PR would be nice.

**Comment by maciejwalkowiak** [comment]
I reuse `@EnableWireMock` in a following way - create a custom "slice" annotation that's meta annotated with `@SpringBootTest` or any other Spring context test annotation and then just use this slice annotation in my tests:


```java
@Target(ElementType.TYPE)
@Retention(RetentionPolicy.RUNTIME)
@SpringBootTest
@EnableWireMock(@ConfigureWireMock(
    baseUrlProperties = {
        "app.client-apis.product-aggregate-api.base-path",
        "app.client-apis.rpt-product-api.base-path",
        "app.client-apis.ntz-usage-information-api.base-path",
        "app.client-apis.kmw-participations-api.base-path",
        "app.client-apis.rpt-services-api.base-path"
    }))
@ActiveProfiles("test")
public @interface IntegrationTest {
}
```

```java
@IntegrationTest
class MyServiceTest {
  @Test
  void foo() {
    ..
  }
}
```

**Comment by tomasbjerre** [comment]
I pushed an example test case using that meta annotation. Perhaps that solves the issue @rfelgent ?

**Comment by rfelgent** [comment]
Hi,

I will try your setup @maciejwalkowiak.

If it is working, I am not sure whether to or not to invest time for meta-annotation support @tomasbjerre

**Comment by tomasbjerre** [comment]
I'll close this issue. Open again if you think something more needs to be done here.

**Comment by rfelgent** [comment]
Hi @maciejwalkowiak and @tomasbjerre ,

your suggestion does not work in my case. My integration test wants to inejct the `WebTestClient` for RESTful assertions. Do you have a working example with an injected `WebTestClient` ?

This is my custom meta-annotation

```
@Target({ElementType.TYPE})
@Retention(RetentionPolicy.RUNTIME)
@Documented
@Inherited
@SpringBootTest
@DirtiesContext
@TestMethodOrder(MethodOrderer.OrderAnnotation.class)
@ExtendWith({RandomBeansExtension.class})
@Testcontainers
@ComponentScan
@AutoConfigureWebTestClient
@EnableWireMock(
    @ConfigureWireMock(
        baseUrlProperties = {
            "app.client-apis.played-recording-api.base-path",
            "app.client-apis.rpt-services-api.base-path",
            "app.client-apis.ntz-usage-information-api.base-path",
            "app.client-apis.ntz-international-usage-api.base-path",
            "app.client-apis.kmw-participations-api.base-path",
            "app.client-apis.product-aggregate-builder-api.base-path",
            "app.client-apis.product-aggregate-api.base-path",
            "app.vrdb-client.base-path",
            "app.client-apis.delivery.base-path"}))
public @interface SpringBootTestGvl {

}
```

**Comment by tomasbjerre** [comment]
But the WebTestClient should invoke your system under test right? Not WireMock? I dont get your exact use case. Perhaps better to open new issue and describe that in detail.

**Comment by rfelgent** [comment]
hi @tomasbjerre ,

the situation is like this: 

- my integration test invokes a restful api of the application under test (my app) via WebTestClient
- the code behind the restful api of my app invokes another 3rd party RESTful api (stubbed via WireMock)

If I use RestAssured like your example tests, everything is working fine. But I do like the `WebTestClient` of spring boot and I would like to keep it instead of replacing it by other client, e.g. RestAssured.

**Comment by rfelgent** [comment]
sorry, i do not understand what you mean ^^

> And the properties contributed points to WireMock.

exactly... so the server side logic of my app code talks to wiremock server.

> But the tests in this repo invokes WireMock

I wanted to make clear, that if I create the client - which is talking to my app - myself (e.g. RestAssured) everything is working fine. But I want to use the `WebTestClient` that is getting created automatically by any `@SpringBootTest`

**Comment by tomasbjerre** [comment]
Would it solve your issue if you create a configuration class like this:

```java
@Configuration
public static class TestConfig {
      @Bean("webTestClientPlayedRecording")
      public WebTestClient webTestClientPlayedRecording(
         @Value("${app.client-apis.played-recording-api.base-path}") String url)
      {
         return  WebTestClient.bindToServer()
            .baseUrl(url)
            .build();
      }
}
```

And in your tests you would inject it with:

```java
@Qualifier("webTestClientPlayedRecording")
@Autowire
WebTestClient webTestClientPlayedRecording;
```

It sounds to me like a very strange use case. Only reason I can imagine for doing this is to invoke the WireMock admin API. And I think most users will want to use the WireMock client to interact with WireMock.
