### ISSUE TITLE
Http and https on same instance

### ISSUE THREAD

**Issue by dogruis** [wiremock/wiremock-spring-boot#62]
### Proposal

With your 3.1.0 version I have to use
`@EnableWireMock{{@ConfigureWireMock(port = 8081)}, @ConfigureWireMock(useHttps = true, port = 8082)}`
To have http and https enabled

I would prefer to use

`@EnableWireMock(@ConfigureWireMock(port = 8081, httpsPort = 8082)`

This would save me from having the need to spin up two wiremock instances.

Edit: I don't know if you have access to this documentation but it need to be updated to reflect your changes.
https://wiremock.org/docs/solutions/spring-boot/

**Comment by tomasbjerre** [comment]
Do you have any suggestions for naming the properties?

**Comment by dogruis** [comment]
I think it should follow the same naming convention as the wiremock-standalone project:
https://wiremock.org/docs/junit-jupiter/
`httpPort` and `httpsPort`

Or here
https://github.com/wiremock/wiremock/blob/master/src/main/java/com/github/tomakehurst/wiremock/core/WireMockConfiguration.java

**Comment by tomasbjerre** [comment]
And if you dont want to have static ports. How do you want to enable it?

**Comment by dogruis** [comment]
Generally I only need http or https. In some cases I want both but then I specify the static port numbers.

**Comment by tomasbjerre** [comment]
Perhaps one way to solve this is to:
- Add new httpsPort option in the annotation
- Make it -1 by default (disabled). Setting it to 0 would be random port and any other value static port.
- Also add new properties for the https port and the https base url
- Probably remove the enableHttps boolean

**Comment by dogruis** [comment]
On top of that with version 3.1.0

`@EnableWireMock{{@ConfigureWireMock(port = 8081)}, @ConfigureWireMock(useHttps = true, port = 8082)}`

When I use this it is breaking my spring application context for some reason.

**Comment by tomasbjerre** [comment]
> On top of that with version 3.1.0
> 
> `@EnableWireMock{{@ConfigureWireMock(port = 8081)}, @ConfigureWireMock(useHttps = true, port = 8082)}`
> 
> When I use this it is breaking my spring application context for some reason.

Probably because they both have the same name. But hard to be sure without your log. I submitted a PR that will give an error when same name is used. #63

**Comment by tomasbjerre** [comment]
PR available with example test case that uses HTTP and HTTPS #64

**Comment by tomasbjerre** [comment]
Also regarding the documentation on the website. I prefer that to be very minimal and refer users to the running examples here in the repository. I think running examples are trustworthy for users and easy to maintain for me.

**Comment by tomasbjerre** [comment]
Released in 3.2.0

**Comment by dogruis** [comment]
Awesome
