### ISSUE TITLE
Add option to disable stub reset after each test method

### ISSUE THREAD

**Issue by djjorjinho** [wiremock/wiremock-spring-boot#70]
### Proposal

Support a wiremock server option to selectively disable stub reset.

`spring-cloud-contract` already supports this [option](https://docs.spring.io/spring-cloud-contract/reference/project-features-wiremock.html), maybe this project can support the same?

**Comment by tomasbjerre** [comment]
Should be a simple feature to add.

Just curious about the use case. When is this needed?

**Comment by djjorjinho** [comment]
> Just curious about the use case. When is this needed?

I want to use this to debug an issue I'm having with concurrent test execution at the class and method level. My tests rely on a correlation id header and don't clash with each other, but I have tests failing with 404 if they run concurrently, even with a `@DirtiesContext` annotation.

I can raise an issue or a feature for this situation as well, but I would like to understand what is actually happening first, because these tests can run fine on certain machines, but fail randomly on others, so I can't effectively replicate this atm. 

So I would like to start debugging with a single mockserver for every service, that runs for the duration of all tests with all necessary stubs; I think it would make the setup deterministic enough for me to wrap my head around what is happening.

**Comment by tomasbjerre** [comment]
@djjorjinho can you have quick look at https://github.com/wiremock/wiremock-spring-boot/pull/71 ? Do you think that will help?

**Comment by djjorjinho** [comment]
@tomasbjerre yes that would work, thanks 🙂

**Comment by tomasbjerre** [comment]
Released it now as `3.4.0`.

**Comment by djjorjinho** [comment]
Many thanks @tomasbjerre 🙏
